# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Reusable workflow to perform update of CSI sidecars.
name: CSI Sidecars Update

# Invocable as a reusable workflow
on:
  workflow_call:

jobs:
  csi-sidecars-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest CSI Sidecar Versions from dell/csm
        run: |
          curl -s https://raw.githubusercontent.com/falfaroc/csm/refs/heads/update-csi-sidecars/config/csm-versions.yaml > versions-content

      - name: CSM docs sidecar update
        if: ${{ github.repository == 'dell/csm-docs' }}
        run: | 
          echo "This is specifically for dell/csm-docs"

      # # Needed for signing commits using Github App tokens
      # # See: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#commit-signing
      # - name: Generate GitHub App Token
      #   uses: actions/create-github-app-token@v2.0.6
      #   id: generate-token
      #   with:
      #     app-id: ${{ vars.CSM_RELEASE_APP_ID }}
      #     private-key: ${{ secrets.CSM_RELEASE_APP_PRIVATE_KEY }}

      # # Must enable "allow GitHub Actions to create pull requests" setting
      # # Author defaults to the user who triggered the workflow run
      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     token: ${{ steps.generate-token.outputs.token }}
      #     branch: "update-csi-sidecars"
      #     commit-message: "Update CSI sidecar versions latest"
      #     title: "Update CSI sidecar versions latest"
      #     body: |
      #       Automated update of CSI sidecar versions.

      #       Auto-generated by [common-github-actions](https://github.com/dell/common-github-actions)
      #     sign-commits: true
      #     delete-branch: true
