# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0


on:
  workflow_dispatch:

jobs:
  release-notes-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Clone io-tools/change-log
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          # Need to retrieve the next milestone.
          MILESTONE=v1.14.0

          git clone https://${GITHUB_TOKEN}@github.com/falfaroc/change-log.git
          cd change-log

          make build

          sed -i "s/milestone: \(.*\)*/milestone: \"$MILESTONE\"/g" config.yaml
          ./bin/change-log > changelog.md

          cat changelog.md
