# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

on:
  workflow_call:

jobs:
  release-notes-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone io-tools/change-log
        env:
          GITHUB_TOKEN: ${{ secrets.INTERNAL_GITHUB_TOKEN }}
        run: |
          git clone https://eos2git.cec.lab.emc.com/io-tools/change-log.git
          cd change-log
          git checkout main
          cd ..
